version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 869935096522.dkr.ecr.us-east-2.amazonaws.com
      - pip install pipenv
      - pipenv install --dev
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t blacklist/container-repository .
      - docker tag blacklist/container-repository:latest 869935096522.dkr.ecr.us-east-2.amazonaws.com/blacklist/container-repository:latest
      - echo Build completed on `date`
      - echo Running unit tests...
      - FLASK_ENV=testing SECRET_TOKEN=secretoken pipenv run pytest --cov=src
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 869935096522.dkr.ecr.us-east-2.amazonaws.com/blacklist/container-repository:latest
      - echo Writing Image Definitions file...
      - printf '[{"name":"container-blacklist","imageUri":"869935096522.dkr.ecr.us-east-2.amazonaws.com/blacklist/container-repository:latest"}]' > imagedefinitions.json
      - printf '{"ImageURI":"869935096522.dkr.ecr.us-east-2.amazonaws.com/blacklist/container-repository:latest"}' > imageDetail.json
      - cat imagedefinitions.json
artifacts:
  files:
    - "**/*"
    - imagedefinitions.json
    - imageDetail.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.json
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json
